# %RAML 1.0 NamedExample
value:
  -
    repairID: 150
    staff: 2 
    partName: Motherboard
    partType: A
    amount: 90
    repairPrice: 921
    dor: 2015-05-23
    computer: 2
  -
    repairID: 155
    staff: 2
    partName: Cooler
    partType: B
    amount: 21
    repairPrice: 90.9
    dor: 2015-05-23
    computer: 3