# %RAML 1.0 NamedExample
value:
  -
    staffID: 1
    firstName: Joshua 
    lastName: Marks
    active: true
    pid: '41251851'
    address: 65th Street
    gender: male
    city: NYC
    username: johsma
    dob: 2015-05-23
  -
    staffID: 2
    firstName: Michaela 
    lastName: Marks
    active: true
    pid: '41252251'
    address: 65th Street
    gender: female
    city: NYC
    username: mkmarks
    dob: 2015-05-23